#!/usr/bin/perl
#
# A script to auto-increment sequence number files.
#
# Written for the MIT Libraries by Eric Celeste, December 1996.

use Getopt::Std;

getopts('f:n:t:i', \my %opts);

$filename = $opts{f};
$notes = $opts{n} ? $opts{n} : "no note";
$type = $opts{t} ? $opts{t} : "";

open(IN,"<$filename") || die "Could not read file \"$filename\".\n";

($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst)=localtime(time);
$mon++;
$year += 1900;
$date = sprintf("%04d%02d%02d%06d",$year,$mon,$mday,"0");

while (<IN>) {
        ($seq,$ignore) = split /\./;
}

$seq++;
$seq = sprintf("%03d",$seq);

print "$seq.$date\n";

close(IN);

if ($opts{i}) {
        # write the new number back to the file
        open(OUT,">>$filename") || die "Could not write to \"$filename\".\n";
        print OUT "$seq.$date $notes $type\n";
        close(OUT);
}
